autoload:
  infra:
    name:           infra
    path:           %SF_MODEL_LIB_DIR%/../../../infra
#    prefix:         1
    recursive:      on   
    
  plugins:
    name:           plugins
    path:           %SF_MODEL_LIB_DIR%/../../../plugins
    recursive:      on   
    
    
  propel:
    name:           propel
    path:           %SF_MODEL_LIB_DIR%/../../../vendor/propel
#    prefix:         1
    recursive:      on   
    
    
  zend:
    name:           zend
    path:           %SF_MODEL_LIB_DIR%/../../../vendor/ZendFramework/library
#    prefix:         1
    recursive:      on   
